<b>Python Implementation of Logistic Regression (Binomial)</b>

• Case Study: We have a dataset that holds the information of various
users from the social Networks. An automobile manufacturer recently
launched a new SUV vehicle. As a result, the company wanted to check
how many users from the dataset would like to purchase the car.
• For this problem
− we will build a Machine Learning model using the Logistic regression algorithm.
The dataset is shown in the below image. In this problem, we will predict
the purchased variable (Dependent Variable) by using age and salary
(Independent variables).

<b>Steps in Logistic Regression</b>

1. Data Pre-processing step
2. Fitting Logistic Regression to the Training set
3. Predicting the test result
4. Test accuracy of the result(Creation of Confusion matrix)
5. Visualizing the test set result.

1:Data Pre-processing step & Initialization


#importing the libraries

In [65]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [66]:
#loading data

In [67]:
dataset = pd.read_csv('User_Data.csv')
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [68]:
#Data Pre-processing step

In [69]:
#• Extracting Independent and dependent Variable

In [70]:
x= dataset.iloc[ : , [2,3 ] ].values
y= dataset.iloc[ : , 4].values

we have taken [2, 3] for x because our independent variables are <b>age and salary, which
are at index 2, 3. And we have taken 4 for y variable because our dependent variable is
at index 4.</b>

In [71]:
#Splitting the dataset into training and test set.

In [72]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.25, random_state = 0)

In [73]:
#Initialization Data Pre-processing step

it is very important to perform
feature scaling here because Age
and Estimated Salary values lie in
different ranges. If we don’t scale
the features then Estimated Salary
feature will dominate Age feature
when the model finds the nearest
neighbor to a data point in data
space

In [74]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
xtrain = sc_x.fit_transform(xtrain)
xtest = sc_x.transform(xtest)

In [75]:
print (xtrain[0:10, :])

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]]


In logistic regression, we will do feature scaling because we want accurate result of
predictions.<b>Here we will only scale the independent variable because dependent variable have
only 0 and 1 values</b>

Fitting Logistic Regression to the Training set

• Here once see that Age and Estimated salary features values are
sacled and now there in the -1 to 1. Hence, each feature will contribute
equally in decision making i.e. finalizing the hypothesis.

In [76]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(xtrain,ytrain)


LogisticRegression(random_state=0)

<b>Fitting Logistic Regression to the Training set</b>

• Prediction on Testing Data


− Our model is well trained on the training set, so we will now predict the result by
using test set data. Below is the code for it:

In [77]:
y_pred = classifier.predict(xtest)

In [78]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

<b>Test Accuracy of the result</b>

Creating the Confusion matrix

In [79]:
from sklearn.metrics import confusion_matrix
cm= confusion_matrix(ytest,y_pred)
cm

array([[65,  3],
       [ 8, 24]], dtype=int64)

out of 100:
TP+TN= 65+24=89
FP+FN=3+8=11

we can interpret that
− 65+24= 89 <b>(Correct Output),<b/>
− and 8+3= 11(Incorrect Output).

<b>Test Accuracy of the result</b>

• Accuracy measures the proportion of true results to total cases.
− Aim for a high accuracy rate.
• Accuracy is a common evaluation metric for classification problems.
It’s the number of correct predictions made as a ratio of all predictions
made.

<b>− accuracy = # correct predictions / # total data points</b>
− Overall, how often is the classifier correct?
➢ Accuracy = (TP+TN)/total

In [80]:
from sklearn.metrics import accuracy_score
print("accuracy score:", accuracy_score(ytest,y_pred))

accuracy score: 0.89


In [81]:
from sklearn import svm

<b>Test Accuracy of the result</b>

• Misclassification Rate(Error Rate): Overall, how often is it wrong.
Since accuracy is the percent we correctly classified (success rate), it
follows that our error rate (the percentage we got wrong) can be
calculated as follows:
− Misclassification Rate = (FP+FN)/total

In [82]:
from sklearn.metrics import zero_one_score

y_pred = svm.predict(test_samples)
accuracy = zero_one_score(y_test, y_pred)
error_rate = 1 - accuracy

ImportError: cannot import name 'zero_one_score' from 'sklearn.metrics' (C:\Users\user\anaconda3\envs\machinelachel\lib\site-packages\sklearn\metrics\__init__.py)